#if !canImport(ObjectiveC)
import XCTest

extension Base58SwiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Base58SwiftTests = [
        ("testBase58CheckDecoding", testBase58CheckDecoding),
        ("testBase58CheckDecodingWithInvalidCharacters", testBase58CheckDecodingWithInvalidCharacters),
        ("testBase58CheckDecodingWithInvalidChecksum", testBase58CheckDecodingWithInvalidChecksum),
        ("testBase58CheckEncoding", testBase58CheckEncoding),
        ("testBase58DecodingForInvalidStrings", testBase58DecodingForInvalidStrings),
        ("testBase58DecodingForValidStrings", testBase58DecodingForValidStrings),
        ("testBase58EncodingForValidStrings", testBase58EncodingForValidStrings),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Base58SwiftTests.__allTests__Base58SwiftTests),
    ]
}
#endif
